### ISSUE TITLE
Port to WebExtensions

### ISSUE THREAD

**Issue by MikkCZ** [klemens/ff-flashdisable#12]
Is this add-on possible to port to WebExtensions API? If there are no APIs for Flash plugin state manipulation, maybe it can block downloading of all Flash content instead, which should have the same effect if Flash plugin is enabled in the add-ons manager.

**Comment by klemens** [comment]
I don't think there will be an API for managing plugins, as flash will be the only remaining plugin soon and will always be set to "ask to activate".
Preventing the download of flash content is probably not a good idea, as the website will just break then. Maybe it will be possible to hide the fact that flash is installed by using a content script in a WebEx, just like it [currently does](https://github.com/klemens/ff-youtube-all-html5/blob/35ec8a8c/data/youtube-html5.js#L125-L158) using the addon-sdk. I think the `unsafeNavigator` will not be available, but maybe this can be replaced by [injecting scripts](https://github.com/klemens/ff-youtube-all-html5/blob/4a56b2533/data/youtube-video-quality.js#L164-L192). However I am not sure how this interacts with things like [CSP](https://en.wikipedia.org/wiki/Content_Security_Policy).

**Comment by MikkCZ** [comment]
AFAIK WebExtensions scripts should not be limited by any CSP and similar limitations etc. So far I know about some cookies restrictions when 3rd part cookies are disabled, but that's probably a bug I will investigate and report soon.

**Comment by klemens** [comment]
For reference: A web extension API for disabling flash [was declined](https://bugzilla.mozilla.org/show_bug.cgi?id=1364931), because the user can change the state through the addon manager.
